### ISSUE TITLE
Packaging the DefauleManager through generics can cause memory leaks?

### ISSUE THREAD

**Issue by ETmanwenhan** [asowers1/CodableCache#7]
Packaging the DefauleManager through generics can cause memory leaks?

```swift
final class DefauleManager<T: Codable> {
    
    let cache: CodableCache<T>
    
    init(cacheKey: AnyHashable) {
        cache = CodableCache<T>(key: cacheKey)
    }
    
    func get() -> T? {
        return cache.get()
    }
    
    func set(_ value: T) throws {
        try? cache.set(value: value)
    }
    
}
```

**Comment by asowers1** [comment]
Hi, Thanks for your question. Could you supply more information? I've been running a demo application where I call get and set with some value repeatedly and receive no memory leak. Are you sure that you're not strongly capturing something within your own objects that you get and set within CodableCache? It's not the responsibility of CodableCache to manage the memory _within_ your objects.

**Comment by asowers1** [comment]
Hey, is this still an issue for you?

**Comment by ETmanwenhan** [comment]
No，Thank you！
